[package]
name = "cellarium"
version = "0.3.0"
edition = "2024"

[features]
default = ["cuda"]
cuda = ["dep:cudarc"]

[dependencies]
cudarc = { version = "0.19.9", optional = true, default-features = false, features = ["std", "driver", "nvrtc", "fallback-dynamic-loading", "cuda-11080"] }
image = { version = "0.25", default-features = false }
rand = "0.9"
ron = "0.10"
robust = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
eframe = { version = "0.36.1", features = ["persistence"] }
wgpu = "30.0.1"
bytemuck = "1.25.2"
pollster = "1.0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
egui_kittest = { version = "0.36.1", features = ["wgpu", "snapshot", "eframe"] }
libc = "0.2"
