[package]
name = "cellarium"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
cudarc = { version = "0.19.9", default-features = false, features = ["std", "driver", "nvrtc", "fallback-dynamic-loading", "cuda-11080"] }
image = { version = "0.25", default-features = false }
ratatui-image = { version = "11.0.6", default-features = false, features = ["crossterm"] }
ratatui = "0.30.2"
rand = "0.9"
thiserror = "2"

[dev-dependencies]
libc = "0.2"
