[package]
name = "cellarium"
version = "0.1.14"
edition = "2024"

[features]
default = ["cuda"]
cuda = ["dep:cudarc"]

[dependencies]
base64 = "0.22"
crossterm = "0.29.0"
cudarc = { version = "0.19.9", optional = true, default-features = false, features = ["std", "driver", "nvrtc", "fallback-dynamic-loading", "cuda-11080"] }
image = { version = "0.25", default-features = false }
ratatui-image = { version = "11.0.6", default-features = false, features = ["crossterm"] }
ratatui = "0.30.2"
rand = "0.9"
ron = "0.10"
robust = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
unicode-width = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
libc = "0.2"
