//! WGSL generation for the portable compute backend.
//!
//! Shaders are emitted from the typed Growth AST, never by pasting user source
//! into WGSL. User identifiers do not survive: every symbol becomes a dense
//! slot, so a program cannot collide with a WGSL keyword or reach outside the
//! validated language.

use std::fmt::Write as _;

use crate::sim::compute_plan::ComputePlan;
use crate::sim::growth::ast::{BinaryOp, UnaryOp};
use crate::sim::growth::types::{TypedBinding, TypedExpr, TypedExprKind, TypedProgram, ValueType};
use crate::sim::local_backend::BackendFailure;

/// A generated shader plus the entry points a pipeline should look up.
#[derive(Clone, Debug, PartialEq)]
pub struct GeneratedWgsl {
    pub source: String,
    /// One growth function per binding, in plan order.
    pub entry_points: Vec<String>,
    /// Dense slot names for each binding's growth inputs, in signature order.
    pub symbol_slots: Vec<Vec<String>>,
}

pub fn generate_wgsl(plan: &ComputePlan) -> Result<GeneratedWgsl, BackendFailure> {
    let mut source = String::new();
    source.push_str(WGSL_PRELUDE);
    let mut entry_points = Vec::with_capacity(plan.bindings.len());
    let mut symbol_slots = Vec::with_capacity(plan.bindings.len());

    for (index, binding) in plan.bindings.iter().enumerate() {
        let name = format!("growth_{index}");
        if binding.frozen {
            // A frozen channel keeps its value; emitting the identity keeps one
            // function per binding so dispatch indices stay aligned.
            let _ = writeln!(
                source,
                "fn {name}(self_value: f32) -> f32 {{\n    return self_value;\n}}\n"
            );
            entry_points.push(name);
            symbol_slots.push(vec!["self_value".into()]);
            continue;
        }
        let program = binding.program.as_ref().ok_or_else(|| {
            BackendFailure::Unsupported(format!(
                "binding {index} has no typed growth program to generate"
            ))
        })?;
        let (function, slots) = emit_function(&name, program, binding)?;
        source.push_str(&function);
        entry_points.push(name);
        symbol_slots.push(slots);
    }

    Ok(GeneratedWgsl {
        source,
        entry_points,
        symbol_slots,
    })
}

/// Helpers WGSL does not provide with the semantics the language defines.
const WGSL_PRELUDE: &str = "// Generated by Cellarium. Do not edit.\n\
fn cellarium_gauss(x: f32, mu: f32, sigma: f32) -> f32 {\n\
\x20   return exp(-0.5 * pow((x - mu) / sigma, 2.0));\n\
}\n\n";

fn emit_function(
    name: &str,
    program: &TypedProgram,
    binding: &crate::sim::compute_plan::CompiledBinding,
) -> Result<(String, Vec<String>), BackendFailure> {
    // Externals are addressed by dense slot. Kernel potentials and `self` become
    // parameters; declared parameters are compile-time constants of this binding
    // and are folded in as literals.
    let ordered = program.externals.ordered();
    let mut slots = Vec::with_capacity(ordered.len());
    let mut signature = Vec::new();
    for (index, symbol) in ordered.iter().enumerate() {
        if index < program.externals.kernel_inputs.len() {
            let slot = format!("k{index}");
            signature.push(format!("{slot}: f32"));
            slots.push(slot);
        } else if symbol == "self" {
            signature.push("self_value: f32".to_string());
            slots.push("self_value".to_string());
        } else {
            let value = binding.parameters.get(symbol).copied().ok_or_else(|| {
                BackendFailure::Unsupported(format!("growth parameter {symbol} has no value"))
            })?;
            slots.push(wgsl_float(value)?);
        }
    }

    let mut body = String::new();
    let mut temporary = 0;
    for statement in &program.bindings {
        emit_binding(statement, &slots, &mut temporary, &mut body)?;
    }
    let result = emit_expr(&program.result, &slots, &mut temporary)?;
    body.push_str(&result.statements);

    let mut function = String::new();
    let _ = writeln!(function, "fn {name}({}) -> f32 {{", signature.join(", "));
    for line in body.lines() {
        let _ = writeln!(function, "    {line}");
    }
    let _ = writeln!(function, "    return {};", result.expression);
    function.push_str("}\n\n");
    Ok((function, slots))
}

struct Emitted {
    statements: String,
    expression: String,
}

fn emit_binding(
    binding: &TypedBinding,
    slots: &[String],
    temporary: &mut usize,
    output: &mut String,
) -> Result<(), BackendFailure> {
    let value = emit_expr(&binding.value, slots, temporary)?;
    output.push_str(&value.statements);
    let _ = writeln!(
        output,
        "let s{}: {} = {};",
        binding.id.0,
        wgsl_type(binding.value.ty),
        value.expression
    );
    Ok(())
}

fn emit_expr(
    expression: &TypedExpr,
    slots: &[String],
    temporary: &mut usize,
) -> Result<Emitted, BackendFailure> {
    let plain = |expression: String| Emitted {
        statements: String::new(),
        expression,
    };
    match &expression.kind {
        TypedExprKind::Constant(value) => Ok(plain(wgsl_float(*value)?)),
        TypedExprKind::Bool(value) => Ok(plain(value.to_string())),
        TypedExprKind::Symbol(id) => Ok(plain(
            slots
                .get(id.0 as usize)
                .cloned()
                .unwrap_or_else(|| format!("s{}", id.0)),
        )),
        TypedExprKind::Unary { op, operand } => {
            let operand = emit_expr(operand, slots, temporary)?;
            let op = match op {
                UnaryOp::Neg => "-",
                UnaryOp::Not => "!",
            };
            Ok(Emitted {
                statements: operand.statements,
                expression: format!("({op}({}))", operand.expression),
            })
        }
        TypedExprKind::Binary { op, lhs, rhs } => {
            let lhs = emit_expr(lhs, slots, temporary)?;
            let rhs = emit_expr(rhs, slots, temporary)?;
            let mut statements = lhs.statements;
            statements.push_str(&rhs.statements);
            let expression = match op {
                BinaryOp::Power => format!("pow({}, {})", lhs.expression, rhs.expression),
                _ => format!(
                    "(({}) {} ({}))",
                    lhs.expression,
                    binary_operator(op),
                    rhs.expression
                ),
            };
            Ok(Emitted {
                statements,
                expression,
            })
        }
        TypedExprKind::Call { name, arguments } => {
            let mut statements = String::new();
            let mut values = Vec::with_capacity(arguments.len());
            for argument in arguments {
                let argument = emit_expr(argument, slots, temporary)?;
                statements.push_str(&argument.statements);
                values.push(argument.expression);
            }
            Ok(Emitted {
                statements,
                expression: call_expression(name, &values)?,
            })
        }
        TypedExprKind::If {
            condition,
            then_branch,
            then_result,
            else_branch,
            else_result,
        } => {
            // WGSL has no if-expression, so the value lands in a var that both
            // arms assign. Each arm keeps its own scope, matching the language.
            let condition = emit_expr(condition, slots, temporary)?;
            let slot = *temporary;
            *temporary += 1;

            let mut statements = condition.statements;
            let _ = writeln!(statements, "var t{slot}: {};", wgsl_type(expression.ty));
            let _ = writeln!(statements, "if ({}) {{", condition.expression);
            emit_branch(
                then_branch,
                then_result,
                slots,
                temporary,
                slot,
                &mut statements,
            )?;
            statements.push_str("} else {\n");
            emit_branch(
                else_branch,
                else_result,
                slots,
                temporary,
                slot,
                &mut statements,
            )?;
            statements.push_str("}\n");
            Ok(Emitted {
                statements,
                expression: format!("t{slot}"),
            })
        }
    }
}

fn emit_branch(
    bindings: &[TypedBinding],
    result: &TypedExpr,
    slots: &[String],
    temporary: &mut usize,
    slot: usize,
    output: &mut String,
) -> Result<(), BackendFailure> {
    let mut body = String::new();
    for binding in bindings {
        emit_binding(binding, slots, temporary, &mut body)?;
    }
    let result = emit_expr(result, slots, temporary)?;
    body.push_str(&result.statements);
    let _ = writeln!(body, "t{slot} = {};", result.expression);
    for line in body.lines() {
        let _ = writeln!(output, "    {line}");
    }
    Ok(())
}

fn binary_operator(op: &BinaryOp) -> &'static str {
    match op {
        BinaryOp::Add => "+",
        BinaryOp::Subtract => "-",
        BinaryOp::Multiply => "*",
        BinaryOp::Divide => "/",
        BinaryOp::Equal => "==",
        BinaryOp::NotEqual => "!=",
        BinaryOp::Less => "<",
        BinaryOp::LessEqual => "<=",
        BinaryOp::Greater => ">",
        BinaryOp::GreaterEqual => ">=",
        BinaryOp::And => "&&",
        BinaryOp::Or => "||",
        BinaryOp::Power => "*",
    }
}

/// Every documented built-in, mapped to WGSL with the same semantics the CPU
/// reference implements.
fn call_expression(name: &str, values: &[String]) -> Result<String, BackendFailure> {
    let one = |function: &str| (values.len() == 1).then(|| format!("{function}({})", values[0]));
    let result = match name {
        "sqrt" => one("sqrt"),
        "abs" => one("abs"),
        "exp" => one("exp"),
        "log" => one("log"),
        "sin" => one("sin"),
        "cos" => one("cos"),
        "tanh" => one("tanh"),
        "floor" => one("floor"),
        "ceil" => one("ceil"),
        "round" => one("round"),
        "sign" => one("sign"),
        "min" if values.len() == 2 => Some(format!("min({}, {})", values[0], values[1])),
        "max" if values.len() == 2 => Some(format!("max({}, {})", values[0], values[1])),
        "step" if values.len() == 2 => Some(format!("step({}, {})", values[0], values[1])),
        "clamp" if values.len() == 3 => Some(format!(
            "clamp({}, {}, {})",
            values[0], values[1], values[2]
        )),
        "smoothstep" if values.len() == 3 => Some(format!(
            "smoothstep({}, {}, {})",
            values[0], values[1], values[2]
        )),
        "mix" if values.len() == 3 => {
            Some(format!("mix({}, {}, {})", values[0], values[1], values[2]))
        }
        "gauss" if values.len() == 3 => Some(format!(
            "cellarium_gauss({}, {}, {})",
            values[0], values[1], values[2]
        )),
        _ => None,
    };
    result.ok_or_else(|| {
        BackendFailure::Unsupported(format!(
            "growth function {name} with {} arguments has no WGSL form",
            values.len()
        ))
    })
}

fn wgsl_type(ty: ValueType) -> &'static str {
    match ty {
        ValueType::Scalar => "f32",
        ValueType::Bool => "bool",
    }
}

fn wgsl_float(value: f32) -> Result<String, BackendFailure> {
    if !value.is_finite() {
        return Err(BackendFailure::Unsupported(
            "growth constants must be finite".into(),
        ));
    }
    Ok(format!("f32({value:?})"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sim::compute_plan::compile_compute_plan;
    use crate::sim::experiment_model::{ChannelId, ExperimentSpec};
    use crate::sim::ruleset::BindingKey;

    fn plan_with_source(source: &str) -> ComputePlan {
        let mut spec = ExperimentSpec::single_channel_lenia(4, 4)
            .normalize_rules()
            .unwrap();
        let binding = BindingKey {
            basis: spec.basis_ids()[0],
            output: ChannelId(0),
        };
        let rule_set = spec.rules.detach(binding).unwrap();
        let rule = spec.rules.get_mut(rule_set).unwrap();
        rule.kernels[0].symbol = "k1".into();
        rule.growth.source = source.to_string();
        compile_compute_plan(&spec).unwrap()
    }

    fn validate(source: &str) -> Result<(), String> {
        let module = wgpu::naga::front::wgsl::parse_str(source)
            .map_err(|error| format!("parse: {error:?}"))?;
        wgpu::naga::valid::Validator::new(
            wgpu::naga::valid::ValidationFlags::all(),
            wgpu::naga::valid::Capabilities::all(),
        )
        .validate(&module)
        .map_err(|error| format!("validate: {error:?}"))?;
        Ok(())
    }

    #[test]
    fn rate_value_branches_emit_typed_wgsl_without_user_identifiers() {
        let plan = plan_with_source("let x = k1 * 2; if x > 1 { -self } else { x }");
        let wgsl = generate_wgsl(&plan).unwrap();
        assert!(wgsl.source.contains("fn growth_0"));
        assert!(wgsl.source.contains("select(") || wgsl.source.contains("if ("));
        assert!(!wgsl.source.contains("let x ="));
    }

    #[test]
    fn generated_shaders_pass_naga_validation() {
        for source in [
            "self",
            "let x = k1 * 2; if x > 1 { -self } else { x }",
            "gauss(k1, 0.15, 0.015) * 2 - 1",
            "clamp(k1 + self, 0, 1)",
            "if k1 >= 0.5 && self < 0.9 { 1 } else { 0 }",
            "min(max(k1, 0), 1) * mix(0, self, 0.5)",
            "sqrt(abs(k1)) + tanh(self) - sign(k1)",
            "let a = k1; let b = a * a; b ^ 2",
        ] {
            let plan = plan_with_source(source);
            let wgsl = generate_wgsl(&plan).unwrap();
            validate(&wgsl.source).unwrap_or_else(|error| {
                panic!("{source:?} produced invalid WGSL: {error}\n{}", wgsl.source)
            });
        }
    }

    #[test]
    fn every_binding_gets_one_entry_point_in_plan_order() {
        let plan = plan_with_source("self");
        let wgsl = generate_wgsl(&plan).unwrap();
        assert_eq!(wgsl.entry_points.len(), plan.bindings.len());
        for (index, entry) in wgsl.entry_points.iter().enumerate() {
            assert_eq!(entry, &format!("growth_{index}"));
            assert!(wgsl.source.contains(&format!("fn {entry}(")));
        }
    }

    #[test]
    fn growth_inputs_become_dense_slots_rather_than_user_names() {
        let plan = plan_with_source("k1 + self");
        let wgsl = generate_wgsl(&plan).unwrap();
        // Kernel potentials and `self` are parameters; declared parameters are
        // constants of this binding and are folded in as literals.
        assert_eq!(wgsl.symbol_slots[0][0], "k0");
        assert_eq!(wgsl.symbol_slots[0][1], "self_value");
        assert!(
            wgsl.symbol_slots[0][2..]
                .iter()
                .all(|slot| slot.starts_with("f32(")),
            "declared parameters should be folded constants: {:?}",
            wgsl.symbol_slots[0]
        );
        assert!(wgsl.source.contains("k0: f32"));
        assert!(!wgsl.source.contains("k1:"));
    }

    #[test]
    fn a_frozen_binding_emits_the_identity_so_indices_stay_aligned() {
        let spec = ExperimentSpec::single_channel_lenia(4, 4)
            .normalize_rules()
            .unwrap();
        let spec =
            crate::document::channels::set_channel_frozen(&spec, ChannelId(0), true).unwrap();
        let plan = compile_compute_plan(&spec).unwrap();
        let wgsl = generate_wgsl(&plan).unwrap();
        assert_eq!(wgsl.entry_points.len(), plan.bindings.len());
        assert!(wgsl.source.contains("return self_value;"));
        validate(&wgsl.source).unwrap();
    }

    #[test]
    fn a_non_finite_constant_is_refused_before_a_pipeline_is_built() {
        assert!(wgsl_float(f32::INFINITY).is_err());
        assert!(wgsl_float(f32::NAN).is_err());
    }
}
